# Generated by Django 4.2 on 2023-04-11 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0003_manager_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('surname', models.CharField(max_length=300)),
                ('username', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=300)),
                ('password', models.CharField(max_length=300)),
                ('img', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='Manager',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.AddField(
            model_name='comment',
            name='username',
            field=models.CharField(default='Anonymous', max_length=300),
        ),
        migrations.AddField(
            model_name='voucher',
            name='img',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='voucher',
            name='like',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='voucher',
            name='rate',
            field=models.CharField(default='', max_length=300),
        ),
    ]
